### ISSUE TITLE
Blender: todo

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/MeshSync#95]
- [x] fix visibility handling
- [x] fix parent handling
- [x] add 'bake transform' option
- [x] fix auto sync
- [ ] improve detecting updated objects (bpy.app.handlers.depsgraph_update_post)
- [ ] use render meshes (Subdivision modifier has both render/viewport iterations)
- [ ] fix bone handling (can reproduce by tree_creature.blend )
- [ ] handle textures
- [ ] materials
- [ ] multiple uv support (#92)
- [ ] send preview mesh when editing
- [ ] greasepen
- [ ] drop 2.79 support (2019/10~)

**Comment by sasa42** [comment]
Hi.
Is there a rough ETA of the multiple UV support?

**Comment by sindharta** [comment]
Moving to https://github.com/Unity-Technologies/MeshSyncDCCPlugin/issues/6
